-- 코드를 입력하세요
SELECT PRD.PRODUCT_CODE, SUM(OS.SALES_AMOUNT*PRD.PRICE) AS SALES
FROM PRODUCT PRD
JOIN OFFLINE_SALE OS ON PRD.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY PRD.PRODUCT_ID
ORDER BY SUM(OS.SALES_AMOUNT*PRD.PRICE) DESC, PRD.PRODUCT_CODE;